### ISSUE TITLE
animation freeze on scroll

### ISSUE THREAD

**Issue by gmoulin** [jonobr1/diagonalFade#1]
on the demo page with FF4 the fade animation freeze when scrolling

**Comment by jonobr1** [comment]
Thanks for the find. Would you happen to have any suggestions on resolving this? To my knowledge I dont know how to override this pause of execution during scrolling. Seems like this is the case for Safari as well. I'll do some research and look into this further.

**Comment by gmoulin** [comment]
Do you bind a listener on scroll event ?

**Comment by jonobr1** [comment]
no, but should I?

I use `animate()` and I think that pauses when scrolling. If that's the case then it's the problem. I'm gonna post a S/O question.
