### ISSUE TITLE
k[u * l + r] is undefined

### ISSUE THREAD

**Issue by darce** [jonobr1/diagonalFade#5]
Hello!
I've set up a really minimal scenario with a div holding a set of images, each with a "width" and "height" attribute defined in the html.
Whenever I try to run the function, I get the error above.

curiousdevice/sprawl_test/index2.html

I don't think that I'm missing anything, and I'm out of ideas. Hopefully some fresh eyes would help.

Thanks!
Daniel + Angela.

**Comment by darce** [comment]
curiousdevice.com, sorry

**Comment by jonobr1** [comment]
Is this the latest build? i.e when did you download this? My only guess is that this is an old version of diagonalFade one which doesn't account for [imperfect grids](https://github.com/jonobr1/diagonalFade/commit/3a653b7bd4590b19e5a5bd23ef4e2a40020cadb3).

The other thing it could be is that you have to give `#test` a defined width so diagonalFade can determine how many `img`'s to a row. Hope that helps.

**Comment by darce** [comment]
Thanks!
Yes, that seems to be the problem.
Is it necessary to define a width for the images in the html or can it be done in css?
--Daniel.

**Comment by jonobr1** [comment]
Off the top of my head I don't think so... :\

I think it reads the pixel value of the width for the moment that `diagonalFade` is called
