### ISSUE TITLE
Width / Height of Container and children not taking account of marging /padding

### ISSUE THREAD

**Issue by watabol** [jonobr1/diagonalFade#6]
hi dude,
Thanks for your awsome plugins. Just used it and love it :)
Anyway, had some issues considering my container width/height, and same for my children's width/height.

I changed your code on line 49 :

// Abstract this to check all elements
var w = children[0].offsetWidth;
var h = children[0].offsetHeight;

// Calculate rows and Columns for our Matrix
var m = parseInt(ch / h);
var n = parseInt(cw / w);

By the following :

 // Abstract this to check all elements
var w = $(children[0]).outerWidth(true);//take account of padding / margin
var h = $(children[0]).outerHeight(true);//take account of padding / margin

// Calculate rows and Columns for our Matrix
var n = Math.floor(cw / w);//take account of container over width
var m = Math.floor(ch / h);//take account of container over height

I'm using dynamic resize so my container width is not always equal of one row width.
Hope this cna helps other followers.
Cheers,
Bastien Besson

**Comment by jonobr1** [comment]
Glad you like the plugin and good suggestion! I added this to the latest build.
