### ISSUE TITLE
Browser / mobile support and performance

### ISSUE THREAD

**Issue by stereokai** [jonobr1/diagonalFade#7]
Hi, this script looks amazing on the demo page!

I saw the last major commit was on May 4th 2011. Therefore I was wondering, did you have the chance to test it against for browser support on desktop and/or mobile lately? And at all?

Where there any performance issues on any platform?

I appreciate your response.

**Comment by jonobr1** [comment]
Hey,

Thanks for writing and glad you like diagonalFade. I've only tested it on my personal machines:
- 2010 MacBookPro Chrome, Safari, Firefox
- iOS 5 iPhone 4 Chrome, Safari
- HP Touchsmart Internet Explorer 9, Chrome, Firefox

All seem to be running the [demo page](http://jonobr1.github.com/diagonalFade/) fine. Were there additional performance tests you were thinking of — like how many total items you could fade?

**Comment by stereokai** [comment]
I was thinking more in the direction of fading in divs with rich content — such as other nested divs, text, images - you know, your everyday HTML template. Currently I'm using my own recursive function. It looks like this:

```
                var posts = $('.nf-column > div');
                var i = 0;
                jQuery.fx.interval = 3;

                function serialFadeIn () {
                    if (i < posts.length) {

                        var fadeIn = function (i) {
                            $(posts[i]).fadeIn();
                        }

                        var ii = i;
                        setTimeout(function () {
                            fadeIn(ii);
                        }, i * 100);

                        i++;
                        serialFadeIn();
                    } else {
                        return; }
                }
```

What do you think? :)

(edit: I can't seem to get syntax highlighting on this one)

**Comment by jonobr1** [comment]
Hey @stereokai sorry for the delay. In theory that looks fine... it's a bit difficult to hypothesize on pseudo code, but ultimately it depends on the content. The script itself is light, but if there are +1,000 elements it will become slow. If those elements are `.swf`'s or animated `canvas`'s then it will be far less than that. As far as I can tell there aren't many absolute metrics on this. Unfortunately this is a natural obstacle with developing for the web.

My recommendation is to test it yourself on as many different setups as you can and start to create a standard for yourself. When it gets down to it you may have to make some tough decisions
